
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.PrintJob;
import java.awt.Toolkit;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.DriverManager;
import java.util.*;
import javax.swing.*;
import java.sql.*;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hp
 */
public class book_ticket extends javax.swing.JFrame {

    /**
     * Creates new form book_ticket
     */
    public book_ticket() {
        initComponents();
        FillCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        Printpanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tctry = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cb3 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        pnr1 = new javax.swing.JTextField();
        tdoft = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tadd = new javax.swing.JTextField();
        tst = new javax.swing.JTextField();
        jrdb3 = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cb2 = new javax.swing.JComboBox();
        tid = new javax.swing.JTextField();
        tnm = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cb1 = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jrdb2 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        tclss = new javax.swing.JTextField();
        jrdb1 = new javax.swing.JRadioButton();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tage = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        tprice = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        saveb = new javax.swing.JButton();

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setPreferredSize(new java.awt.Dimension(899, 899));
        getContentPane().setLayout(null);

        Printpanel.setBackground(new java.awt.Color(255, 255, 153));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel7.setText(" Date of Travel");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel14.setText("Arrival time");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel4.setText(" Age");

        tctry.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel10.setText(" ");

        cb3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setText(" Name");

        pnr1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        tdoft.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tdoft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tdoftActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel13.setText(" Flight Company");

        tadd.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        tst.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        buttonGroup1.add(jrdb3);
        jrdb3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jrdb3.setText(" First class");
        jrdb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdb3ActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel16.setText("Departure time");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel11.setText("Class");

        cb2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        tid.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        tnm.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jComboBox2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "22:14", "21:30", "15:30", "18:24" }));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel9.setText("PNR");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setText(" Country");

        cb1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel8.setText(" Flight no");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setText(" Address");

        buttonGroup1.add(jrdb2);
        jrdb2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jrdb2.setText(" Business");
        jrdb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdb2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel5.setText(" ID");

        tclss.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        buttonGroup1.add(jrdb1);
        jrdb1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jrdb1.setText(" Economy");
        jrdb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdb1ActionPerformed(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "12:00", "13:00", "00:13", "01:34" }));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel12.setText("Seat no");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel6.setText(" Destination");

        tage.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel15.setText("Price");

        tprice.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        javax.swing.GroupLayout PrintpanelLayout = new javax.swing.GroupLayout(Printpanel);
        Printpanel.setLayout(PrintpanelLayout);
        PrintpanelLayout.setHorizontalGroup(
            PrintpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PrintpanelLayout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addGroup(PrintpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(PrintpanelLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel1))
                    .addGroup(PrintpanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(PrintpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel12)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(96, 96, 96)
                        .addGroup(PrintpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnr1, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                            .addComponent(tst, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                            .addComponent(tprice))))
                .addGap(10, 53, Short.MAX_VALUE))
            .addGroup(PrintpanelLayout.createSequentialGroup()
                .addGroup(PrintpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel13)
                    .addGroup(PrintpanelLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel10))
                    .addComponent(jLabel16)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78)
                .addGroup(PrintpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tclss, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb2, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tdoft, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tid, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tage, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tctry, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jrdb1)
                    .addComponent(jrdb2)
                    .addComponent(jrdb3)
                    .addComponent(tadd, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tnm, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 53, Short.MAX_VALUE))
        );

        PrintpanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cb1, cb2, cb3, jComboBox1, jComboBox2, jLabel1, jLabel10, jLabel11, jLabel12, jLabel13, jLabel16, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, jLabel8, jLabel9, jrdb1, jrdb2, jrdb3, pnr1, tadd, tage, tclss, tctry, tdoft, tid, tnm, tst});

        PrintpanelLayout.setVerticalGroup(
            PrintpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PrintpanelLayout.createSequentialGroup()
                .addGap(3, 15, Short.MAX_VALUE)
                .addGroup(PrintpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tnm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(PrintpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tadd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(PrintpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PrintpanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel3))
                    .addComponent(tctry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(PrintpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PrintpanelLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel4))
                    .addGroup(PrintpanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(tage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(PrintpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PrintpanelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel5))
                    .addGroup(PrintpanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(tid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(PrintpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PrintpanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel6)
                        .addGap(16, 16, 16)
                        .addComponent(jLabel7)
                        .addGap(13, 13, 13)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addGap(23, 23, 23)
                        .addComponent(jLabel10)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel16))
                    .addGroup(PrintpanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(cb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tdoft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cb3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(PrintpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tclss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(24, 24, 24)
                .addComponent(jrdb1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrdb2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrdb3)
                .addGap(7, 7, 7)
                .addGroup(PrintpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(PrintpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pnr1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(PrintpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tprice, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53))
        );

        PrintpanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cb1, cb2, cb3, jComboBox1, jComboBox2, jLabel1, jLabel10, jLabel11, jLabel12, jLabel13, jLabel14, jLabel16, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, jLabel8, jLabel9, jrdb1, jrdb2, jrdb3, pnr1, tadd, tage, tclss, tctry, tdoft, tid, tnm, tst});

        getContentPane().add(Printpanel);
        Printpanel.setBounds(440, 10, 710, 960);

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton4.setText("Back to main");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(1210, 650, 137, 40);

        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton5.setText(" Print");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(1220, 550, 100, 40);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setText(" Generate PNR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(1200, 880, 160, 60);

        saveb.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        saveb.setText(" Save");
        saveb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebActionPerformed(evt);
            }
        });
        getContentPane().add(saveb);
        saveb.setBounds(1220, 450, 100, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tdoftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tdoftActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tdoftActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         try
       {
        Class.forName("com.mysql.jdbc.Driver");
       //Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/dbms_min_v5","root","ritesh");
       Random ran=new Random();
       int max=10000;
       int min=9350;
        for(int i =1; i<100; i++)
        {
               int randomInteger=ran.nextInt((max-min)+1)+min;
                pnr1.setText(String.valueOf(randomInteger));
        }
       }catch(Exception e){}
   
  
//Read more: https://javarevisited.blogspot.com/2013/05/how-to-generate-random-numbers-in-java-between-range.html#ixzz5SUanOmoM
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void savebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebActionPerformed
        // TODO add your handling code here:
            try
       {
         Class.forName("com.mysql.jdbc.Driver");
       Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/dbms_min_v5","root","ritesh");
      // Statement stmt=con.createStatement();
       PreparedStatement stmt1;
       Random ran1=new Random();
        stmt1=con.prepareStatement("insert into Passenger values(?,?,?,?,?)");
        stmt1.setInt(1,(Integer.parseInt(tid.getText())));
        stmt1.setString(2,tnm.getText());
        stmt1.setString(3,tadd.getText());
        stmt1.setString(4,tctry.getText());
        stmt1.setInt(5,Integer.parseInt(tage.getText()));
        stmt1.executeUpdate();
        stmt1.close();
       
         stmt1=con.prepareStatement("insert into Ticket values(?,?,?,?,?,?");
         String Fno=cb1.getSelectedItem().toString();
          stmt1.setString(5,Fno);
          stmt1.setInt(2,(Integer.parseInt(tid.getText())));
          stmt1.setInt(1,(Integer.parseInt(pnr1.getText())));
          stmt1.setInt(4,(Integer.parseInt(tst.getText())));
          stmt1.setString(3,tclss.getText());
          // for(int i =1; i<100; i++)
            
               //int ranprice=ran1.nextInt((80000-50000)+1)+50000;
                stmt1.setInt(6,Integer.parseInt(tprice.getText()));
            
         stmt1.executeUpdate();
          stmt1.close();
           jrdb1.setActionCommand("Economy");
           jrdb2.setActionCommand("Business");
           jrdb2.setActionCommand("First class");
           //tcls.setText(buttonGroup1.getSelection().getActionCommand());
           
          
          con.close();
           //stmt1.close();
           //stmt.close();
           this.setVisible(false);
       }catch(Exception e){/*JOptionPane.showMessageDialog(null,"Error in connectivity")*/;}
            JOptionPane.showMessageDialog(null,"Inserted ticket details succesfully");
            
    }//GEN-LAST:event_savebActionPerformed
    private void FillCombo()
    {
           try
           {
               Class.forName("com.mysql.jdbc.Driver");
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/dbms_min_v5","root","ritesh");
                
            String sql="Select distinct * from flight";
            Statement stmt=con.createStatement();
            ResultSet rs=stmt.executeQuery(sql);
            while(rs.next())
            {
                    cb1.addItem(rs.getString(4));
                    
                    //cb2.addItem(rs.getString(2));
                    //cb3.addItem(rs.getString(1));
            }
            rs.close();
            stmt.close();
            Statement stmt1=con.createStatement();
            String dest=(String)cb1.getSelectedItem();
            String sql1="Select distinct * from flight where F_departure='"+dest+"'";
            ResultSet rs1=stmt1.executeQuery(sql1);
            while(rs1.next())
            {
                cb2.addItem(rs1.getString(2));
            }
            rs1.close();
            stmt1.close();
            Statement stmt2=con.createStatement();
             String F_comp=(String)cb2.getSelectedItem();
              String sql2="Select distinct * from flight where F_company='"+F_comp+"'";
              ResultSet rs2=stmt2.executeQuery(sql2);
                while(rs2.next())
            {
                cb3.addItem(rs2.getString(1));
            }
                rs2.close();
                stmt.close();
                //JOptionPane.showMessageDialog(null,"Booking Succesfull");
                
           }catch(Exception e){JOptionPane.showMessageDialog(null," comboerror");}
    }
    private void jrdb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdb1ActionPerformed
        // TODO add your handling code here:
        if(jrdb1.isSelected()==true)
        {
            tclss.setText("Economy");
            tprice.setText("20000");
        }
        
    }//GEN-LAST:event_jrdb1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new ticket().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void cb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb1ActionPerformed

    private void jrdb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdb2ActionPerformed
        // TODO add your handling code here:
        if(jrdb2.isSelected()==true)
        {
            tclss.setText("Business");
            tprice.setText("40000");
        }
    }//GEN-LAST:event_jrdb2ActionPerformed

    private void jrdb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdb3ActionPerformed
        // TODO add your handling code here:
        if(jrdb3.isSelected()==true)
        {
            tclss.setText("First Class");
            tprice.setText("50000");
        }
    }//GEN-LAST:event_jrdb3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
       /* Toolkit tkp = Printpanel.getToolkit();
        PrintJob pjp =tkp.getPrintJob(this, null, null);
        Graphics g = pjp.getGraphics();
        Printpanel.print(g);
        g.dispose();
        pjp.end();*/
        PrinterJob job = PrinterJob.getPrinterJob();
            job.setJobName("Print Data");
            
            job.setPrintable(new Printable(){
            public int print(Graphics pg,PageFormat pf, int pageNum){
                    pf.setOrientation(PageFormat.LANDSCAPE);
                 if(pageNum>0){
                    return Printable.NO_SUCH_PAGE;
                }
                
                Graphics2D g2 = (Graphics2D)pg;
                g2.translate(pf.getImageableX(), pf.getImageableY());
               g2.scale(0.999,0.999);
                //g2.dispose();
                Printpanel.paint(g2);
//          
               
                return Printable.PAGE_EXISTS;
                         
                
            }

           // @Override
          /*  public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException 
            {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }*/
    });
         
        boolean ok = job.printDialog();
        if(ok){
        try{
            
        job.print();
        }
        catch (PrinterException ex){}
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(book_ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(book_ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(book_ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(book_ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new book_ticket().setVisible(true);
            }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Printpanel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cb1;
    private javax.swing.JComboBox cb2;
    private javax.swing.JComboBox cb3;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jrdb1;
    private javax.swing.JRadioButton jrdb2;
    private javax.swing.JRadioButton jrdb3;
    private javax.swing.JTextField pnr1;
    private javax.swing.JButton saveb;
    private javax.swing.JTextField tadd;
    private javax.swing.JTextField tage;
    private javax.swing.JTextField tclss;
    private javax.swing.JTextField tctry;
    private javax.swing.JTextField tdoft;
    private javax.swing.JTextField tid;
    private javax.swing.JTextField tnm;
    private javax.swing.JTextField tprice;
    private javax.swing.JTextField tst;
    // End of variables declaration//GEN-END:variables
}
